### ISSUE TITLE
setup.py docs does not work

### ISSUE THREAD

**Issue by Moritz90** [blue-yonder/pyscaffold#142] opened 2018-01-31 14:24 UTC
After creating a new project with pyscaffold, I tried to run `python setup.py docs`. This was the result:

> usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help
> 
> error: invalid command 'build_sphinx'

I then tried running `python setup.py build_sphinx` directly, but this failed as well (output anonymized):

> running build_sphinx
Running Sphinx v1.7.0b2
usage: usage: setup.py [OPTIONS] -o <OUTPUT_PATH> <MODULE_PATH> [EXCLUDE_PATTERN, ...]
setup.py: error: unrecognized arguments: {$dir}/docs/../src/{$module}
> 
> Configuration error:
The configuration file (or one of the modules it imports) called sys.exit()

**Comment by FlorianWilhelm** [comment] 2018-01-31 18:51
Did you install sphinx?

**Comment by FlorianWilhelm** [comment] 2018-02-01 13:15
I could reproduce this in case Sphinx is not installed. Currently PyScaffold tries to install Sphinx locally as egg file but I don't like that solution any more and in Version 3.0 it even breaks. Better is to break directly and tell the user to install Sphinx. So the workaround for you is just to install Sphinx but I will add a better error message.

**Comment by Moritz90** [comment] 2018-02-05 15:12
I can confirm that everything works after manually installing sphinx. I was relying on the documentation which claimed this wasn't necessary.

I guess this is mostly a bug in the documentation, then.

**Comment by FlorianWilhelm** [comment] 2018-02-07 14:55
@Moritz90, thanks for confirming. 

The problem was fixed in commit a4cf5ab8ffaf3195145d069d2b67cf33e86bfbc9, i.e., a more meaningful error message is emitted and the documentation was changed.

**Closed by FlorianWilhelm** 2018-02-07 14:55 UTC
Labels: bug
