### ISSUE TITLE
Can't get test requirements working 

### ISSUE THREAD

**Issue by sebastianneubauer** [blue-yonder/pyscaffold#70] opened 2015-09-15 08:28 UTC
As I found out, additional requirements for tests (e.g. mock) are installed only when a file exists with the magic name `test-requirements.txt`. Having this with only mock as a single requirement seems to hinder the installation of pytest and pythest-cov which are otherwise without this tests-requirements installed automatically. Adding pytest and pytest-cov to requirements fails because it seems that the installation requirements are not resolved correctly:
```
Installed /home/PHI-TPS/sneubauer/Projekte/CrumblePy/crumble_py_bak/.eggs/pytest_cov-2.1.0-py2.7.egg
Traceback (most recent call last):
  File "setup.py", line 24, in <module>
    setup_package()
  File "setup.py", line 20, in setup_package
    use_pyscaffold=True)
  File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/PHI-TPS/sneubauer/Projekte/CrumblePy/venv/local/lib/python2.7/site-packages/pyscaffold/pytest_runner.py", line 91, in run
    self.distribution.fetch_build_eggs(self.distribution.tests_require)
  File "/home/PHI-TPS/sneubauer/Projekte/CrumblePy/venv/local/lib/python2.7/site-packages/setuptools/dist.py", line 313, in fetch_build_eggs
    replace_conflicting=True,
  File "/home/PHI-TPS/sneubauer/Projekte/CrumblePy/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pytest' distribution was not found and is required by the application```

Running then `python setup.py test` afterwards a second time succeeds...
The only workaround I know of atm, is to install pytest into the virtualenv manually before running `python setup.py test`...

**Comment by FlorianWilhelm** [comment] 2015-09-16 14:06
After our discussion this is a duplicate of #71 and the suggested fix for #71 solves this too.

**Closed** 2015-09-16 14:06 UTC
Labels: duplicate
