### ISSUE TITLE
issues with automatic version number

### ISSUE THREAD

**Issue by sebastianneubauer** [blue-yonder/pyscaffold#76] opened 2015-10-09 14:56 UTC
It seems, if the package setup.py is not in the git repository root directory, the generated version string is different than in the root dir:
root dir:
python setup.py --version
0.0.post0.dev1+11079f0
subfolder:
python setup.py --version
0.0.1.dev1

**Comment by FlorianWilhelm** [comment] 2015-10-09 16:15
This is kind of unintended usage. Did everything else work? Can you explain what you exactly did? 
Somehow setuptools_scm switches back to the default versioning.

**Comment by sebastianneubauer** [comment] 2015-10-12 14:46
Mmmh, I feared an answer like this, but in my experience we cannot come around accepting, that the pressure to use pyscaffold is sometimes smaller than the pressure to not have setup.py in the root of a repository. Often for example there are many packages in one repository, because they should have a common version (same version control)...then it makes sense to have them both in subfolders and both have a separate pyscaffold... 
As far as I can see, everything except for the versioning is working...of course in order to be really usefull and intended in this scenario, one should be able to tell pyscaffold not to create a repo...

**Comment by FlorianWilhelm** [comment] 2015-10-12 16:43
Ok, it should be no problem to let PyScaffold only create a repo if the current directory is not already a git repo. The problem is the strange versioning... do you want to look into it? My guess is it is setuptools_scm related. With a debugger it should be no problem to find the cause. I am on holidays right now and cant do it.

**Comment by sebastianneubauer** [comment] 2015-10-12 19:56
Ok, I can have a look...

**Comment by sebastianneubauer** [comment] 2015-10-12 21:27
I analyzed the issue with the versioning and found the reason. Setuptools has a configuration parameter "root" which defaults to ".".
We can quite easily fix this issue by setting the correct root dir. The root folder can be identified with the following:

     repo_dir = subprocess.Popen(['git', 'rev-parse', '--show-toplevel'], stdout=subprocess.PIPE).communicate()[0].rstrip().decode('utf-8')

**Comment by FlorianWilhelm** [comment] 2015-10-13 08:26
Thanks, that was fast. Is this a parameter of setuptools or setuptools_scm? The latter I guess. I'll think with a few changes in integration.py we can resolve this issue. I'll look into it after my holidays.

**Comment by FlorianWilhelm** [comment] 2015-10-27 11:21
Thanks to @treebee this is fixed in release v2.4.3!

**Closed by FlorianWilhelm** 2015-10-27 11:21 UTC
Labels: enhancement
