### ISSUE TITLE
PyScaffold breaks the installation of numpy

### ISSUE THREAD

**Issue by des0ps** [blue-yonder/pyscaffold#99] opened 2017-01-22 08:16 UTC
Installing pyscaffold for python3 prevents the installation of numpy with python 3 support (on MacOS).

Repro steps:

```
pip3 install pyscaffold
brew install numpy --with-python3
```

It gives the following result:

```
Updating Homebrew...
==> Installing numpy from homebrew/python
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Cloning https://github.com/numpy/numpy.git
Cloning into '/Users/Des0ps/Library/Caches/Homebrew/numpy--git'...
remote: Counting objects: 1052, done.
remote: Compressing objects: 100% (1004/1004), done.
remote: Total 1052 (delta 47), reused 306 (delta 20), pack-reused 0
Receiving objects: 100% (1052/1052), 4.27 MiB | 401.00 KiB/s, done.
Resolving deltas: 100% (47/47), done.
==> Checking out branch master
==> Downloading https://files.pythonhosted.org/packages/58/a5/0dc93c3ec33f4e281849523a5a913fa1eea9a30
Already downloaded: /Users/Des0ps/Library/Caches/Homebrew/numpy--nose-1.3.7.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/numpy/HEAD-d25e73
==> Downloading https://files.pythonhosted.org/packages/b7/67/7e2a817f9e9c773ee3995c1e15204f5d01c8da7
######################################################################## 100.0%
==> python -c import setuptools... --no-user-cfg install --prefix=/private/tmp/numpy-20170122-23249-s
==> python setup.py build --fcompiler=gnu95 --parallel=8 install --prefix=/usr/local/Cellar/numpy/HEA
==> python -c import numpy; assert numpy.test().wasSuccessful()
==> Downloading https://files.pythonhosted.org/packages/58/a5/0dc93c3ec33f4e281849523a5a913fa1eea9a30
Already downloaded: /Users/Des0ps/Library/Caches/Homebrew/numpy--nose-1.3.7.tar.gz
==> python3 -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/numpy/HEAD-d25e7
Last 15 lines from /Users/Des0ps/Library/Logs/Homebrew/numpy/05.python3:
    from pbr import util
  File "/usr/local/lib/python3.6/site-packages/pyscaffold/contrib/pbr/pbr/util.py", line 87, in <module>
    import pbr.hooks
  File "/usr/local/lib/python3.6/site-packages/pyscaffold/contrib/pbr/pbr/hooks/__init__.py", line 16, in <module>
    from pbr.hooks import backwards
  File "/usr/local/lib/python3.6/site-packages/pyscaffold/contrib/pbr/pbr/hooks/backwards.py", line 17, in <module>
    from pbr import packaging
  File "/usr/local/lib/python3.6/site-packages/pyscaffold/contrib/pbr/pbr/packaging.py", line 233, in <module>
    from nose import commands
  File "/private/tmp/numpy--nose-20170122-23249-1w4blaa/nose-1.3.7/nose/__init__.py", line 1, in <module>
    from nose.core import collector, main, run, run_exit, runmodule
  File "/private/tmp/numpy--nose-20170122-23249-1w4blaa/nose-1.3.7/nose/core.py", line 153
    print "%s version %s" % (os.path.basename(sys.argv[0]), __version__)
                        ^
SyntaxError: invalid syntax

READ THIS: http://docs.brew.sh/Troubleshooting.html

These open issues may also help:
numpy fails to build with openblas option https://github.com/Homebrew/homebrew-python/issues/359
numpy 1.11.2 fails a test https://github.com/Homebrew/homebrew-python/issues/353
```

Here is the ticket on homebrew-python: https://github.com/Homebrew/homebrew-python/issues/387

**Comment by FlorianWilhelm** [comment] 2017-01-22 10:53
Hi @des0ps, thanks for this report. I actually don't think PyScaffold is the reason for this, it rather seems as if nose got installed in a Python 2 version and this is why `print "%s version %s"` fails with invalid syntax. What happens if you install numpy with pip3?

**Comment by des0ps** [comment] 2017-01-22 13:19
When installing numpy through pip, it works great, it's only when installing the brew formula with the   `--with-python3` parameter.

**Comment by FlorianWilhelm** [comment] 2017-01-22 15:52
Therefore the problem is related to the brew formula and nose, not in any way to PyScaffold. If you agree you can close this issue as resolved.

**Comment by FlorianWilhelm** [comment] 2017-01-22 15:57
@des0ps, could also check why your Python3 environment actually pulls packages from `/private/tmp/numpy--nose-20170122-23249-1w4blaa/nose-1.3.7/nose/`, this is kind of strange. Are you using conda or virtualenv btw? or is brew using `/private`? I think your setup is a bit messy.

**Comment by HolgerPeters** [comment] 2017-01-25 13:11
If I may add, it is a bad idea to mix a package manager with pip. I.e. typically you would always use python virtualenvs for installing such packages. If several tools (brew/pip/apt/easy_install) use the same tree in the file system, it is only to be expected that there will be errors.

**Closed** 2017-01-26 09:04 UTC
